# Generated by Django 5.0.6 on 2024-06-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_category_product_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shippingaddress",
            options={"verbose_name_plural": "Addresses"},
        ),
        migrations.AlterField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
